# permissions to do viewer merakisources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: merakisource-viewer-role
rules:
- apiGroups:
  - dns.jossware.com
  resources:
  - merakisources
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dns.jossware.com
  resources:
  - merakisources/status
  verbs:
  - get
