# permissions to do edit merakisources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: merakisource-editor-role
rules:
- apiGroups:
  - dns.jossware.com
  resources:
  - merakisources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dns.jossware.com
  resources:
  - merakisources/status
  verbs:
  - get
  - patch
  - update
